;; Implement a representation of line segments in a plane.

(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (print-point p)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (make-segment start end)
  (cons start end))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))
(define (print-segment s)
  (print-point (start-segment s))
  (display " -> ")
  (print-point (end-segment s)))

(define (average x y)
  (/ (+ x y) 2))
(define (midpoint-segment s)
  (make-point (average (x-point (start-segment s))
                       (x-point (end-segment s)))
              (average (y-point (start-segment s))
                       (y-point (end-segment s)))))

(print-point (midpoint-segment (make-segment (make-point -3 3)
                                               (make-point 2 2))))
