;; Exercise 1.15.  The sine of an angle (specified in radians) can be computed
;; by making use of the approximation $\sin{x} \approx x$ if x is sufficiently
;; small, and the trigonometric identity
;;
;; \begin{equation}
;; \sin{x} = 3 \sin{\frac{x}{3}} - 4 \sin^3{\frac{x}{3}}
;; \end{equation}
;;
;; to reduce the size of the argument of sin. (For purposes of this exercise an
;; angle is considered ``sufficiently small'' if its magnitude is not greater
;; than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

;; a.  How many times is the procedure p applied when (sine 12.15) is
;; evaluated?

;;; p is called once for every reduction of the argument to sin. Since the
;;; argument to sin is divided by 3 each time until reaching 0.1, we have
;;; $12.15 \times 3^{-n} \leq 0.1$, giving $n \geq 4.37$, or 5 calls to p.


;; b.  What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

;;; Since sine is not in a tail-call position when being called within its
;;; definition, the order of space growth is directly proportional to the
;;; number of steps to compute the sine, which is
;;; $\lceil \log_3{a / 0.1} \rceil$.
